### ISSUE TITLE
Problem with column dimensions (keywords TDIM##) in FITS Tables

### ISSUE THREAD

**Issue by mservillat** [atpy/atpy#19]
It seems the keyword TDIM## used in the description of FITS Table columns in the header is not handled by ATpy (v0.9.5.3). This allows values in a column to be an array with multiple dimensions, while it is stored as a 1D array. I had this issue with a LDAC FITS Table generated by Sextractor which includes the VIGNET column (image snapshot for each detection, so a 2D array).

Try the following test table:
http://hea-www.harvard.edu/~servilla/files/sexcat_test.fits

Then in ipython:
import atpy
t1=atpy.TableSet('sexcat_test.fits')
t1.write('sexcat_test_atpy.fits')
import pyfits
t2=pyfits.open('sexcat_test.fits')
t3=pyfits.open('sexcat_test_atpy.fits')
'TDIM32' in t2[2].header.keys()
'TDIM32' in t3[2].header.keys()

The last line returns 'False' indicating that ATpy lost the keyword (column 32 is the VIGNET column), and thus the true dimensions of the array.

**Comment by astrofrog** [comment]
The dimension of the array are still be preserved, as the TDIM argument is not needed. The information is in TFORM32, which is set to `6400E`, meaning there are 6400 elements. If I view the output file in fv, it still appears to have a 2D array for the VIGNET column. Are there tools that are not working properly because TDIM is missing?

**Comment by mservillat** [comment]
Hi Tom,

the length is fine indeed, but the shape is lost. Yes, this is a
problem when using the Sextractor catalog with PSFEx for example
(which have to use a Sextractor like fits file with the VIGNET
columns): the small images given in the VIGNET column (2D, 80x80=6400)
become 1D vectors of 6400 elements... so not an image anymore.

How can fv recover the shape without the TDIM keyword? when I try to
open a VIGNET from the atpy output file, it plots it in 1D, while it
should call it "Image" and show it as an image.

Cheers,
Mat

On Mon, Jul 25, 2011 at 10:14 PM, astrofrog
reply@reply.github.com
wrote:

> The dimension of the array are still be preserved, as the TDIM argument is not needed. The information is in TFORM32, which is set to `6400E`, meaning there are 6400 elements. If I view the output file in fv, it still appears to have a 2D array for the VIGNET column. Are there tools that are not working properly because TDIM is missing?
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/atpy/atpy/issues/19#issuecomment-1651316

## 

Mathieu Servillat

**Comment by astrofrog** [comment]
Oh, so each _cell_ is a 2D array to start with? It's true that ATpy doesn't deal with that for now. I'll keep this ticket open as a feature request.

**Comment by mservillat** [comment]
that's right, each element in the column is a 2D array (here this VIGNET column)

there are probably 2 steps in addressing this issue:
1/ keep the TDIM keyword, so at least you don't mess up the table for
other programs. I guess that's an easy fix, but also an urgent one as
the table can become unusable after being saved by atpy (I should just
look at the code to suggest a modification...)
2/ when this TDIM keyword indicates more than 1D, the array should be
reshaped to be used directly as e.g. an image in python, and then
reconverted to a 1D vector with the associated TDIM keyword. But then
I guess you have to make it compatible with other formats handled by
atpy...

Note that pyfits just gives the 1D array, as it is recorded in the
fits file (the shape is kept only in the TDIM keyword). However,
pyfits also keeps all the keywords, so the shape is preserved for
other programs.

Mat

On Tue, Jul 26, 2011 at 3:10 PM, astrofrog
reply@reply.github.com
wrote:

> Oh, so each _cell_ is a 2D array to start with? It's true that ATpy doesn't deal with that for now. I'll keep this ticket open as a feature request.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/atpy/atpy/issues/19#issuecomment-1657444

## 

Mathieu Servillat
36 Highland Ave, Apt 43
Cambridge, MA 02139

## +1 617 401 1076

**Comment by astrofrog** [comment]
Oh, I understand now. Can you try removing `'TDIM'` from the list on line 186 of atpy/fitstable.py in the latest version of ATpy and see if that helps? (there have been a few additions at the top of the file recently, so make sure you work from the most recent version)

**Comment by astrofrog** [comment]
The change I suggested would work, but I need to think about this a little more, because if the columns are re-arranged then the TDIM needs to follow (which it wouldn't in the above example).

**Comment by astrofrog** [comment]
The Astropy `Table` class should not have this issue, so I suggest using that instead. It would be too difficult to fix this in ATpy.
