### ISSUE TITLE
Writing CDS tables

### ISSUE THREAD

**Issue by keflavich** [atpy/atpy#20]
"At the moment, asciitable only supports reading in tables, not writing."

I'd like to be able to write files compliant with the CDS submission requirements:
http://cds.u-strasbg.fr/doc/submit.htx
so that I can create digital tables.  I'll give it a go myself in a fork, but I think this feature should be broadly used...

**Comment by astrofrog** [comment]
That message is outdated, as it is possible to call write(..., type='ascii'). I've updated the documentation at http://atpy.github.com/format_ascii.html - however, I don't think asciitable has a CDSWriter class at this stage, so you may want to open a ticket in the asciitable repo requesting a CDSWriter.

**Comment by taldcroft** [comment]
A CDS writer patch for asciitable would be great!

**Comment by astrofrog** [comment]
Closing this ticket since this is asciitable related. However, once the CDS writer works in asciitable, I can add support for type='cds' for Table.write().
