### ISSUE TITLE
t.describe() on empty Table raises an AttributeError

### ISSUE THREAD

**Issue by cdeil** [atpy/atpy#22]
I would have expected 'This table is empty' instead of an Error.

In [81]: atpy.**version**
Out[81]: '0.9.5.3'

In [82]: t = atpy.Table()

In [83]: t.describe()
## Table has no name

AttributeError                            Traceback (most recent call last)
/Users/deil/work/workspace/galpop/src/scripts/fermi/diffuse_inner_galaxy/<ipython-input-83-139da4aa6588> in <module>()
----> 1 t.describe()

/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/atpy/basetable.pyc in describe(self)
    693             len_formats_max = 4, 4, 4, 6
    694 
--> 695         for name in self.names:
    696             len_name_max = max(len(name), len_name_max)
    697             len_unit_max = max(len(str(self.columns[name].unit)), len_unit_max)

/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/atpy/basetable.pyc in **getattr**(self, attribute)
    269 
    270         if attribute == 'names':
--> 271             return self.**dict**['data'].dtype.names
    272         elif attribute == 'units':
    273             print "WARNING: Table.units is depracated - use Table.columns to access this information"

AttributeError: 'NoneType' object has no attribute 'dtype'

**Comment by astrofrog** [comment]
Thanks for reporting this - as you can see above, this is now fixed in the git repository and will work properly in the next stable release.
