### ISSUE TITLE
atpy does not recognize np._string values as file names

### ISSUE THREAD

**Issue by hamogu** [atpy/atpy#23]
Hi,

I encountered the following bug: The first argument of `atpy.Table()` needs to be a string. atpy throws and error if it is not a python string, but a numpy string:

> t = atpy.Table(spec)
> 
> type(spec)
>     <type 'numpy.string_'>

This is due to `basetable.py`, where the type is explicitly checked:

```
> .../atpy/basetable.py(196)read()
-> raise Exception('Could not determine table type')
(Pdb) l
191             if 'type' in kwargs:
192                 table_type = kwargs.pop('type').lower()
193             elif type(args[0]) == str:
194                 table_type = atpy._determine_type(args[0], verbose)
195             else:
196  ->             raise Exception('Could not determine table type')
```

`elif (type(args[0]) == str) or (type(args[0]) == np.string)` would fix it. However, I tried to come up with a more generic solution, but could not find one.
For now I just use  `t = atpy.Table(str(spec))`.

**Comment by astrofrog** [comment]
Thanks for reporting this - for info, the best way is:

```
if isinstance(variable, basestring):
```
