### ISSUE TITLE
Feature Request: Merging Tables

### ISSUE THREAD

**Issue by keflavich** [atpy/atpy#24]
I'd like to see some features to merge tables.  Since there are whole languages dedicated to that process, I don't imaging it is terribly straightforward, but I have a very simplistic implementation of "merge items with the same value in column X":

https://github.com/keflavich/atpy/commit/3700d975414ce420427c6224b82d838e343dcc06

Another obvious one is "search for objects within a distance of coordinates specified by columns x,y".   Since I'll soon need this one myself, I'll probably write it up.   I can set up pull requests later, but for now I'd like to hear whether this is a feature you want to see in atpy and what form it should take / where it should be put into the code.

**Comment by astrofrog** [comment]
This is something we definitely want to do, and in fact I've already written a function to do this: https://gist.github.com/877990 - could you test this out and see whether it does what you want? I'm planning on working on it a bit more and integrating it into ATpy, but it needs more testing.

**Comment by astrofrog** [comment]
Regarding the coordinate matching, I think in the long run we want support for coordinates in ATpy, but we need to think first about how this should be implemented. If you end up coding something up for this, let us know!

**Comment by taldcroft** [comment]
Just my two cents, but I think that specific functions related to astronomical coordinates belongs in a coords library, not in a table library.  Defining a representation of coordinates opens a huge can of worms.

**Comment by phn** [comment]
If we just want to search for objects within a certain distance, is there a need to specify the actual coordinate system? As long as the (x, y) values are angles on a sphere, their separation from another in the same system can be found. 

If this is the use case, then the module https://gist.github.com/1111712 may be of help. It has functions and class methods for calculating separations and bearings on a sphere. I have tested it against SLALIB routines and the values agree.

**Comment by taldcroft** [comment]
x might be "+1h20m32s" or whatever.  That's what I mean by coordinate representation.  You might even have (x,y) as coordinates in a WCS tangent plane projection on a part of the sky in which case (x,y) are not necessarily in degrees.  The module you wrote is potentially a good start in the right direction, but again all this should not be glopped into a table manipulation package.

**Comment by phn** [comment]
I agree with you on not mixing coords facilities with atpy. Perhaps there should be a discussion on how to proceed with a corods package. The astrolib.coords is not being maintained anymore, AFAIK.

**Comment by astrofrog** [comment]
I agree that ATpy shouldn't have to do coordinate or even fuzzy matching on simple floats for now. In my view, it is the role of a coordinate package to provide a routine to merge two arrays of coordinates, which could then be used together with ATpy, e.g.:

```
# Read in reference table
tref = atpy.Table(...)

# Read in table to filter
t = atpy.Table(...)

# Find distance to nearest reference object
d = coords.distance_to_nearest_object(tref['ra'], tref['dec'], t['ra'], t['dec'])

# Filter table
t = t.where(d < 1. / 3600.)
```

**Comment by astrofrog** [comment]
By the way, you might be interested in @hamogu's ATpy extensions, see e.g. https://github.com/hamogu/atpy-extensions/blob/master/catalog.py

**Comment by astrofrog** [comment]
I'm closing this since table merging now exists in Astropy, and new features will no longer be developed for ATpy.
