### ISSUE TITLE
Can't write bool data to MySQL

### ISSUE THREAD

**Issue by cdeil** [atpy/atpy#33]
```
t = Table(name='atpy')
t.add_column('bool', np.zeros(2, 'bool'))
t.write('mysql', ...)
```

results in `KeyError: <type 'numpy.bool_'>`, although MySQL can store BOOL data.

I have the same problem (having to convert by hand) with unicode string columns, e.g.

```
t.add_column('unicode', [u'uni', u'code'])
```

results in 

```
KeyError: <type 'numpy.unicode_'>
```

although with unicode I'm not 100% sure if this should work with MySQL.

**Comment by astrofrog** [comment]
Sorry for the delay - could you check whether booleans now work as expected with SQL databases? (we don't support unicode columns at this point)

**Comment by cdeil** [comment]
It works not. Thanks!
