### ISSUE TITLE
DATETIME support for MySQL tables

### ISSUE THREAD

**Issue by cdeil** [atpy/atpy#40]
I am reading a MySQL table with TIMESTAMP and DATETIME, which are converted to 'S64' strings.

I get these warnings:

``` text
Auto-detected table type: sql
WARNING: need to define reverse type for datetime
         Please report this on the ATpy forums!
         This type has been converted to a string
WARNING: need to define reverse type for datetime
         Please report this on the ATpy forums!
         This type has been converted to a string
/Users/deil/Library/Python/2.7/lib/python/site-packages/numpy/core/records.py:157: DeprecationWarning: DType strings 'O4' and 'O8' are deprecated because they are platform specific. Use 'O' instead
  dtype = sb.dtype(formats, aligned)
/Users/deil/Library/Python/2.7/lib/python/site-packages/numpy/core/records.py:157: DeprecationWarning: DType strings 'O4' and 'O8' are deprecated because they are platform specific. Use 'O' instead
  dtype = sb.dtype(formats, aligned)
/Users/deil/Library/Python/2.7/lib/python/site-packages/numpy/core/records.py:157: DeprecationWarning: DType strings 'O4' and 'O8' are deprecated because they are platform specific. Use 'O' instead
  dtype = sb.dtype(formats, aligned)
```

**Comment by astrofrog** [comment]
Could you give an example of what one of these strings looks like? I am wondering whether I should just define that datetime objects get converted to strings explicitly (to remove the message), or whether there is a way to convert them to something else (float, datetime, etc.).

**Comment by cdeil** [comment]
They look like this: `2003-06-11 16:01:30`

Using MySQLdb directly I get a `datetime.datetime(2003, 6, 11, 15, 56, 28)`, not a string.

It seems that a numpy datetime dtype was added only very recently:
http://docs.scipy.org/doc/numpy/reference/arrays.datetime.html

**Comment by astrofrog** [comment]
ATpy does not support Numpy object columns, so I'm going to have to leave it so it converts datetime entries to strings. You can always use the datetime module in Python to convert them to a datetime object.
