### ISSUE TITLE
MySQL -> FITS doesn't work for string columns

### ISSUE THREAD

**Issue by cdeil** [atpy/atpy#43]
I am using atpy to dump MySQL tables to FITS. Sometimes if there are string columns the resulting FITS file is corrupt, even though there is no warning from atpy.

Here's a small test case that shows the problem on my machine:

``` python

opts = dict(host=xxx, user=xxx, passwd=xxx, db=xxx)

from atpy import Table
name = 'atpy_test'
# Create an example table in a MySQL database
table = Table(name=name)
#table.add_column('int_col', [1])
table.add_column('string_col', ['one'])
table.write('mysql', overwrite=True, **opts)
table.write('table.fits', overwrite=True)
print type(table.data), type(table.data[0]), table.data
# Read table from MySQL database and write to FITS file
table2 = Table('mysql', table=name, **opts)
table2.write('table2.fits', overwrite=True)
print type(table2.data), type(table2.data[0]), table2.data
```

The output:

``` text
<type 'numpy.ndarray'> <type 'numpy.void'> [('one',)]
<type 'numpy.ndarray'> <type 'numpy.void'> [('one',)]
```

And here's what ftverify has to say:

``` text
$ ftverify table2.fits 

               ftverify 4.16 (CFITSIO V3.290)               
               ------------------------------               

HEASARC conventions are being checked.

File: table2.fits

2 Header-Data Units in this file.

=================== HDU 1: Primary Array ===================

 5 header keywords

 Null data array; NAXIS = 0 

=================== HDU 2: BINARY Table ====================

*** Error:   Keyword #11, TNULL1: value = None is not an integer. The value is
             entered as a string. 
*** Error:   Keyword #11, TNULL1 is used for the column with format "3A ".

 13 header keywords

 ATPY_TEST  (1 columns x 1 rows)

 Col# Name (Units)       Format
   1 string_col           3A        

++++++++++++++++++++++ Error Summary  ++++++++++++++++++++++

 HDU#  Name (version)       Type             Warnings  Errors
 1                          Primary Array    0         0     
 2     ATPY_TEST            Binary Table     0         2     
```

Note that `table.fits` is OK according to ftverify. atpy can open `table2.fits` for this case, but for my actual data atpy can't open the FITS file it wrote (is this AttributeError a separate issue?):

``` text
Traceback (most recent call last):
  File "scripts/make_tables.py", line 154, in <module>
    monitor_tables.expand()
  File "scripts/make_tables.py", line 92, in expand
    table = Table(filename, type=self.type)
  File "/Users/deil/Library/Python/2.7/lib/python/site-packages/atpy/basetable.py", line 167, in __init__
    self.read(*args, **kwargs)
  File "/Users/deil/Library/Python/2.7/lib/python/site-packages/atpy/basetable.py", line 213, in read
    atpy._readers[table_type](self, *args, **kwargs)
  File "<string>", line 2, in read
  File "/Users/deil/Library/Python/2.7/lib/python/site-packages/atpy/decorators.py", line 36, in _auto_download_to_file
    return read(table, filename, *args, **kwargs)
  File "<string>", line 2, in read
  File "/Users/deil/Library/Python/2.7/lib/python/site-packages/atpy/decorators.py", line 76, in _auto_fileobj_to_file
    return read(table, filename, *args, **kwargs)
  File "/Users/deil/Library/Python/2.7/lib/python/site-packages/atpy/fitstable.py", line 164, in read
    data = pyfits.rec.recarray.field(hdu.data, i)
AttributeError: 'module' object has no attribute 'rec'
```

ftverify shows many errors, here's the first few:

```
*** Error:   Keyword #39, TNULL10: value = NAN.0 is not an integer. The value
             is entered as a string. 
*** Error:   Keyword #39, TNULL10 is used for the column with format "E ".
*** Error:   Keyword #42, TNULL11: value = NAN.0 is not an integer. The value
             is entered as a string. 
*** Error:   Keyword #42, TNULL11 is used for the column with format "E ".
*** Error:   Keyword #45, TNULL12: value = NAN.0 is not an integer. The value
             is entered as a string. 
*** Error:   Keyword #45, TNULL12 is used for the column with format "E ".
*** Error:   Keyword #48, TNULL13: value = NAN.0 is not an integer. The value
             is entered as a string. 
```

I am using Mac OS X Lion and these package versions:

```
atpy: 0.9.5.3 (actually git master 1906256ab000742209fcf0f3c99cdc25a587135b)
pyfits: 3.1-0.0.dev846
numpy: 1.7.0.dev-3503c5f
```

**Comment by astrofrog** [comment]
You can ignore the errors from fitsverify regarding the TNULL value. The bug causing the error when reading the table back in has now been fixed. Could you try and install the latest version from git to see if it resolves your issues?

**Comment by cdeil** [comment]
It works now.
Thanks!

There's a warning for every FITS file I open now which wasn't there before:

```
In [2]: Table('table.fits')                                                                                                                                                         
Auto-detected table type: fits
WARNING: PendingDeprecationWarning: The get_comment function will be deprecated in a future version.
        Use ``header['COMMENT']`` instead. [astropy.utils.misc]
Out[2]: <Table name='ATPY_TEST' rows=1 fields=1>
```

**Comment by astrofrog** [comment]
The issue with the warning should be fixed as of 98ce84bb8262ba585791fa81955d746b228f327a. Could you check whether you are still seeing the warning?

**Comment by nhinkel** [comment]
Hi.  I'm now getting a similar error when I use atpy on a fits files:

```
table =  atpy.Table("test.fit", type="fits")
/usr/local/Cellar/python/2.7.3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/atpy/fitstable.py:194: PendingDeprecationWarning: The get_comment function will be deprecated in a future version.
        Use ``header['COMMENT']`` instead.
  for comment in header.get_comment():
```

I'm on a Mac 10.8.2, python 2.7.3, atpy version 0.9.6.  

Thanks.

**Comment by astrofrog** [comment]
@nhinkel - could you try updating to the latest git version to see if this resolves your issue? This was fixed after 0.9.6 was released. To update:

```
git clone git://github.com/atpy/atpy
cd atpy
python setup.py install
```

**Comment by nhinkel** [comment]
Hi - I followed your instructions and, unfortunately, got the following error when trying to import atpy:

```
In [1]: import atpy
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-f42298aadf45> in <module>()
----> 1 import atpy

/usr/local/Cellar/python/2.7.3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/atpy/__init__.py in <module>()
----> 1 from .basetable import Table, TableSet, VectorException
      2 from .masked import __masked__, set_masked_default
      3 from .version import __version__
      4 

/usr/local/Cellar/python/2.7.3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/atpy/basetable.py in <module>()
     13 from .structhelper import append_field, drop_fields
     14 from .odict import odict
---> 15 from . import registry
     16 from .masked import __masked__
     17 

/usr/local/Cellar/python/2.7.3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/atpy/registry.py in <module>()
    162     return table_type
    163 
--> 164 from . import fitstable
    165 
    166 register_reader('fits', fitstable.read)

/usr/local/Cellar/python/2.7.3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/atpy/fitstable.py in <module>()
      6 
      7 import numpy as np
----> 8 from astropy.io import fits
      9 
     10 from .exceptions import TableException

ImportError: No module named astropy.io
```

**Comment by astrofrog** [comment]
Ah yes, sorry, the development version of ATpy has switched to relying on Astropy. Since Astropy is not yet publicly released, it may be easiest to downgrade back to 0.9.6 by just downloading the tar file and installing that, and then ignore the warning (it's just a warning, but it's harmless).

If instead you are interested in trying out Astropy, then you can install it with:

```
git clone http://github.com/astropy/astropy.git
cd astropy
python setup.py install
```

although note that if you want to do that, you will first need to ensure cython (http://cython.org/) is installed. If you try that, let me know if you have any issues!

**Comment by ghost** [comment]
Hi astrofrog,
I tried to install with your way:

git clone http://github.com/astropy/astropy.git
cd astropy
python setup.py install

but when I start python and try to import atpy, I always get the import error message:
ImportError: No module named astropy.io

Could you please help me???

Thank you!!

**Comment by ebressert** [comment]
@Lilianna do you have astropy installed?

**Comment by ghost** [comment]
@ebressert no I don't think so! 
and another interesting thing is I have python2.6 and python2.7, and I could install atpy in this way on 2.6 but never work for 2.7!

**Comment by ebressert** [comment]
@Lilianna try to install Astropy (new version just came out today) and see if your problem is resolved. Regarding the Python 2.6 and Python 2.7 problem, I would need to know a bit more about your OS and Python setup.

**Comment by ghost** [comment]
@ebressert 
Thank you!!
I installed astropy using: 
pip install astropy
The installation seemed to run correctly, but I don't know on which Python it has been installed, and my problem remains the same. 
Then now I'm trying with git:
git clone git://gitbub.com/astropy/astropy.git
It keeps the step of cloning since 5min, I wonder know if it will work.
I'm on Mac 10.6.8.

**Comment by ghost** [comment]
@ebressert 
Nop git doesn't work! It turns out:

Cloning into 'astropy'...
fatal: unable to connect to gitbub.com:
gitbub.com[0: 199.59.243.105]: errno=Operation timed out
gitbub.com[1: 199.59.243.107]: errno=Operation timed out
gitbub.com[2: 199.59.243.106]: errno=Operation timed out
gitbub.com[3: 199.59.243.109]: errno=Operation timed out
gitbub.com[4: 199.59.243.108]: errno=Operation timed out

**Comment by ghost** [comment]
@ebressert 
There!!! 
I installed successfully astropy and then atpy works!!!
Thank you!!!
Have a nice day!!!

**Comment by ebressert** [comment]
Make sure that that you're cloning from github.com and not gitbub.com ;-). Regarding the Python versions, be careful about installations. Try to stay consistent with the method you install packages, e.g., `python setup.py install` may install packages for a different version of Python vs. `pip install package_name`. 

The problem of the Python versions should be directed to stackoverflow.com as it is not specific to ATpy. But, if you run into other issues with ATpy let us now :).

**Comment by ebressert** [comment]
@Lilianna Great! Good to know that you're all set. Enjoy ATpy!

**Comment by ebressert** [comment]
@astrofrog This issue is still open, but I think we should close it, yes?

**Comment by astrofrog** [comment]
Yes, I think we can close it.
