### ISSUE TITLE
Interface with VizieR

### ISSUE THREAD

**Issue by gellule** [atpy/atpy#47]
Hi,
I would like to contribute an interface to VizieR. I'm thinking of providing an atpy.vizier_service module that would be used with the following syntax. Would atpy be happy to accept this?

```
import atpy.vizier_service

#Find all AGNs in Veron & Cetty with Vmag in [5.0; 14.0]
query = {}
query["-source"] = "VII/258/vv10"
query["Vmag"] = "5.0..14.0"
table1 = atpy.vizier_service.VizieR(query)

#Find sources in 2MASS matching the AGNs positions to within 2 arcsec
query = {}
query["-source"] = "II/246/out" #Catalogue: 2MASS
query["-c.rs"] = "2"
table2 = atpy.vizier_service.VizieR(query, table=table1)
```

**Comment by astrofrog** [comment]
Sorry for not replying to this issue sooner! Is there a reason you closed it?

Your proposal sounds very interesting. We are trying to consolidate online querying code in https://github.com/astropy/astroquery, so maybe you could open a PR there instead of in ATpy?

**Comment by gellule** [comment]
And sorry for closing it without any reason. I was actually looking for a better place for it, and your suggestion is right on. I initially though that astropy/astropy would be a better place, but astropy/astroquery is even better. See you there.

**Comment by astrofrog** [comment]
Closing this since it is in a PR for astroquery (<a href="https://github.com/astropy/astroquery/pull/17">here</a>)
