### ISSUE TITLE
Atpy insists that pyFITS isn't installed, when in fact it is.

### ISSUE THREAD

**Issue by Stargrazer82301** [atpy/atpy#48]
I'm running a fresh install of Python on a Windows 7 machine, The most recent stable versions of atpy and pyFITS are installed and imported.

However, when trying to open a FITS table, I experience the following:

> > > import pyfits
> > > import atpy
> > > t = atpy.Table()
> > > t.read('E:\Meanies.fits')
> > > Auto-detected table type: fits
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "E:\Program Files\Python\lib\site-packages\atpy\basetable.py", line 214, in read
> > >     registry._readers[table_type](self, *args, **kwargs)
> > >   File "<string>", line 2, in read
> > >   File "E:\Program Files\Python\lib\site-packages\atpy\decorators.py", line 38, in _auto_download_to_file
> > >     return read(table, filename, _args, *_kwargs)
> > >   File "<string>", line 2, in read
> > >   File "E:\Program Files\Python\lib\site-packages\atpy\decorators.py", line 78, in _auto_fileobj_to_file
> > >     return read(table, filename, _args, *_kwargs)
> > >   File "E:\Program Files\Python\lib\site-packages\atpy\fitstable.py", line 81, in read
> > >     _check_pyfits_installed()
> > >   File "E:\Program Files\Python\lib\site-packages\atpy\fitstable.py", line 26, in _check_pyfits_installed
> > >     pyfits_minimum_version.vstring + " or later required")
> > > Exception: Cannot read/write FITS files - pyfits 2.1 or later required

Distressing!

**Comment by astrofrog** [comment]
This is strange - could you do:

```
import pyfits
print pyfits.__version__
```

?

Thanks!

**Comment by Stargrazer82301** [comment]
Thanks for your speedy reply. Did as you asked:

> > > import pyfits
> > > print pyfits.**version**

I assume it's not supposed to do that...

As the original error message said that pyfits 2.1 or greater was required,
I found pyfits 2.1.1 on the internet and installed that. When that didn't
fix the issue, I installed the newest version of pyfits again, assuming it
would overwrite anything from the older version. Don't know if that might
give rise to "version ambiguity".

Thanks
CJRC,,

On 30 July 2012 18:31, Thomas Robitaille <
reply@reply.github.com

**Comment by astrofrog** [comment]
I'm not sure - could you do:

```
print pyfits.__path__
```

?

The latest version of PyFITS is 3.0.8:

http://www.stsci.edu/institute/software_hardware/pyfits/Download

**Comment by Stargrazer82301** [comment]
Okay, here's the result:

> > > print pyfits.**path**
> > > ['E:\Program Files\Python\lib\site-packages\pyfits']

3.0.8 is the version I have installed, using the executable installer.

CJRC,,

On 30 July 2012 18:51, Thomas Robitaille <
reply@reply.github.com

**Comment by astrofrog** [comment]
Could you try the following:

```
from distutils import version
pyfits_minimum_version = version.LooseVersion('2.1')
import pyfits
print version.LooseVersion(pyfits.__version__) < pyfits_minimum_version
```

and let me know the output? Thanks!

**Comment by Stargrazer82301** [comment]
Here you go:

> > > from distutils import version
> > > pyfits_minimum_version = version.LooseVersion('2.1')
> > > import pyfits
> > > print version.LooseVersion(pyfits.**version**) < pyfits_minimum_version
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "E:\Program Files\Python\lib\distutils\version.py", line 296, in
> > > **cmp**
> > >     return cmp(self.version, other.version)
> > > AttributeError: LooseVersion instance has no attribute 'version'

**Comment by astrofrog** [comment]
Sorry for the delay - I think this should be fixed now (as of e407e1492b04540b6ff0360dc1c0cdda512d411a). Could you try updating to the latest git version of ATpy and letting me know if that fixed your problem?

**Comment by Stargrazer82301** [comment]
Hi

Not sure if I downloaded the wrong version or somesuch (installed the
version obtained by using the "download as zip" link on the atpy git page),
but I got this:

> > > import atpy
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "E:\Program Files\Python\lib\site-packages\atpy__init__.py", line
> > > 1, in <module>
> > >     from .basetable import Table, TableSet, VectorException
> > >   File "E:\Program Files\Python\lib\site-packages\atpy\basetable.py", line
> > > 15, in <module>
> > >     from . import registry
> > >   File "E:\Program Files\Python\lib\site-packages\atpy\registry.py", line
> > > 164, in <module>
> > >     from . import fitstable
> > >   File "E:\Program Files\Python\lib\site-packages\atpy\fitstable.py", line
> > > 23, in <module>
> > >     if version.LooseVersion(pyfits.**version**) < pyfits_minimum_version:
> > >   File "E:\Program Files\Python\lib\distutils\version.py", line 296, in
> > > **cmp**
> > >     return cmp(self.version, other.version)
> > > AttributeError: LooseVersion instance has no attribute 'version'

**Comment by astrofrog** [comment]
Could you let me know the output of:

```
import pyfits
print pyfits.__version__
print pyfits.__version__ is None
print pyfits.__version__ == ''
```

Thanks!

**Comment by Stargrazer82301** [comment]
Here you go:

> > > import pyfits
> > > print pyfits.**version**
> > > 
> > > print pyfits.**version** is None
> > > False
> > > print pyfits.**version** == ''
> > > True

Chris,,

**Comment by astrofrog** [comment]
Thanks - I think I've fixed it, try again. You can either do the 'download zip', or if you can, use git:

```
git clone git://github.com/atpy/atpy
cd atpy
python setup.py install
```

Any luck?

**Comment by astrofrog** [comment]
@Stargrazer82301 - the latest version of ATpy depends on Astropy. Are you still having issues or can this be closed?

**Comment by Stargrazer82301** [comment]
Works fine for me now, thank you very much.

Chris
