### ISSUE TITLE
table keywords cannot be iterated using key-value pairs

### ISSUE THREAD

**Issue by streeto** [atpy/atpy#49]
One common pattern when iterating dictionaries entries is to use the items() method. The keywords for a table are a dictionary (in fact, a odict), so one would expect to be able to write:

``` python
t = atpy.Table(...)
for k,v in t.keywords.items():
   ...
```

Your odict implementation could add a simple method like the one below to adress this requirement.

``` python
def items(self):
  return zip(self.keys, self.values)
```

**Comment by astrofrog** [comment]
Thanks for the suggestion, this is a good idea. You can already do:

```
for k in t.keywords:
    v = t.keywords[k]
```

but your suggestion is more elegant.

**Comment by astrofrog** [comment]
FYI, I've implemented this - thanks for the suggestion!
