### ISSUE TITLE
Run atpy tests on travis-ci

### ISSUE THREAD

**Issue by cdeil** [atpy/atpy#60]
Does atpy have unit tests?
Can we run them on travis-ci?

@astrofrog Do you have time to write the `.travis.yml` file or should I give it a try?

**Comment by astrofrog** [comment]
ATpy has unit tests, but I'm working on refactoring ATpy into an affiliated package, so we can wait until that's done to add to Travis.

**Comment by astrofrog** [comment]
@cdeil - tests are now running on Travis! :)

**Comment by cdeil** [comment]
Locally I get 41 PGSQL errors. Is this normal or should they succeed or be skipped?

```
E       InternalError: could not connect to server: No such file or directory
E           Is the server running locally and accepting
E           connections on Unix domain socket "/var/pgsql_socket/.s.PGSQL.5432"?

/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pgdb.py:598: InternalError
===================================================================== 41 failed, 123 passed in 3.60 seconds ======================================================================
```

**Comment by astrofrog** [comment]
The tests require a database and user to be set up for the tests - i don't want to just skip them if the test fails since that will make Travis useless. But I'll think of whether we could make them optional and then enable that option on Travis.
